# Generated by Django 5.0.1 on 2024-01-31 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_book_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueditem',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 31, 20, 47, 6, 273309, tzinfo=datetime.timezone.utc)),
        ),
    ]
