# Generated by Django 5.0.1 on 2024-02-01 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_issueditem_isbn_alter_book_book_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subject',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_add_date',
            field=models.DateField(default=datetime.date(2024, 2, 1)),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 1, 13, 15, 12, 314309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issueditem',
            name='issue_date',
            field=models.DateField(default=datetime.date(2024, 2, 1)),
        ),
    ]
