# Generated by Django 5.0.1 on 2024-02-01 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rename_subject_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 1, 14, 17, 7, 202159, tzinfo=datetime.timezone.utc)),
        ),
    ]
